[package]
name = "rusty_rain"
version = "0.1.0"
authors = ["cowboy8625 <cowboy8625@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.5"
rand = "0.7.3"
terminal_size = "0.1.12"
