[package]
name = "rusty-rain"
version = "0.3.4"
authors = ["cowboy8625 <https://github.com/cowboy8625>"]
edition = "2018"
description = "A cross platform CMatrix like program."
readme = "README.md"
repository = "https://github.com/cowboy8625/rusty-rain"
homepage = "https://rusty-rain.xyz"
license-file = "LICENSE"
keywords = ["matrix", "matrix-rain", "emoji", "cmatrix", "rain"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.3"
crossterm = "0.19.0"
rand = "0.8.2"
itertools = "0.10.0"
ezemoji = "0.2.0"

[profile.release]
debug = true
